version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - app-network  # Usar una red definida en lugar de network_mode

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network  # Asegúrate de que ambos servicios estén en la misma red

networks:
  app-network:  # Define la red compartida
    driver: bridge

volumes:
  mongodb-data:
